name: blosc-docs
channels:
  - conda-forge
dependencies:
  - python
  - scikit-build
  - cmake
  - ninja
  - cython
  - msgpack-python
  - httpx

  - sphinx>=8.0.0
  - pydata-sphinx-theme
  - doxygen
  - breathe>=4.35.0
  - numpydoc
  - myst-parser
  - pygments
