name: blosc-docs
channels:
  - conda-forge
dependencies:
  - python
  - scikit-build
  - cmake
  - ninja
  - cython
  - msgpack-python
  - httpx

# Sphinx should be >= 6.2 and < 7.2 (because of breathe)
  - sphinx>=6.2,<7.2
  - pydata-sphinx-theme
  - doxygen
  - breathe>=4.35.0
  - numpydoc
  - myst-parser
  - pygments
