on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ update_website ]
  pull_request:
    branches: [ master ]

jobs:
  build_website:
    runs-on: ubuntu-latest
    name: 'Build website'
    steps:

    # Check out repositories
    - name: Check out website repo
      uses: actions/checkout@v2
    - name: Check out C-Blosc2
      run: git clone https://github.com/Blosc/c-blosc2.git
    - name: Check out Python-Blosc
      run: git clone https://github.com/Blosc/python-blosc.git
    - name: Check out Python-Blosc2
      run: git clone https://github.com/Blosc/python-blosc2.git

    # Install dependencies
    - name: Install dependencies C-Blosc2
      run: pip install -r c-blosc2/doc/requirements.txt
    - name: Install dependencies Python-Blosc
      run: pip install -r python-blosc/requirements_rtfd.txt
    - name: Install Python-Blosc  # Python-Blosc Sphinx conf.py imports blosc, not sure why
      run: pip install -e $(pwd)/python-blosc/
    - name: Install dependencies Python-Blosc2
      run: pip install -r python-blosc2/requirements-doc.txt
    - name: Pin pygments # Sphinx fails without this: 'HtmlFormatter' object has no attribute 'get_linenos_style_defs'
      run: pip install pygments==2.11.2

    # Build websites
    - name: Build Nikola website
      uses: getnikola/nikola-action@v5
      with:
        dry_run: true
    - name: Create artifact directory # The Nikola action creates output/ as root, and it's not writeable
      run: mkdir _site && cp -r output/* _site/
    - name: Build C-Blosc2 docs
      run: sphinx-build -b html c-blosc2/doc/sphinx/source _site/c-blosc2
    - name: Build Python-Blosc docs
      run: sphinx-build -b html python-blosc/doc _site/python-blosc
    - name: Build Python-Blosc2 docs
      run: sphinx-build -b html python-blosc2/doc _site/python-blosc2

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1

  deploy_website:
    needs: build_website
    if: ${{ github.event_name == 'push' || github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    name: 'Deploy website'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
