on: [push]

jobs:
  build_website:
    runs-on: ubuntu-latest
    name: 'Build and deploy website'
    steps:

    # Check out repositories
    - name: Check out website repo
      uses: actions/checkout@v2
    - name: Check out c-blosc2
      run: git clone https://github.com/Blosc/c-blosc2.git
    - name: Check out python-blosc2
      run: git clone https://github.com/Blosc/python-blosc2.git

    # Install dependencies
    - name: Install dependencies c-blosc2
      run: pip install -r c-blosc2/doc/requirements.txt
    - name: Install dependencies python-blosc2
      run: pip install -r python-blosc2/requirements-doc.txt
    - name: Pin pygments # Sphinx fails without this: 'HtmlFormatter' object has no attribute 'get_linenos_style_defs'
      run: pip install pygments==2.11.2

    # Build websites
    - name: Build Nikola website
      uses: getnikola/nikola-action@v3
      with:
        dry_run: true
    - name: Create artifact directory # The Nikola action creates output/ as root, and it's not writeable
      run: mkdir publish && cp -r output/* publish/
    - name: Build c-blosc2 docs
      run: sphinx-build -b html c-blosc2/doc/sphinx/source publish/c-blosc2
    - name: Build python-blosc2 docs
      run: sphinx-build -b html python-blosc2/doc publish/python-blosc2

    # Deploy
    - name: Create blosc website artifact
      uses: actions/upload-artifact@v3
      with:
        name: blosc-website
        path: publish/

