on: [push]

jobs:
  build_website:
    runs-on: ubuntu-latest
    name: 'Build and deploy website'
    steps:

    # Check out repositories
    - name: Check out website repo
      uses: actions/checkout@v2
    - name: Check out c-blosc2
      run: git clone https://github.com/Blosc/c-blosc2.git
    - name: Check out python-blosc2
      run: git clone https://github.com/Blosc/python-blosc2.git
    - name: ls
      run: ls

    # Install dependencies
    - name: Install dependencies c-blosc2
      run: pip install -r c-blosc2/doc/requirements.txt
    - name: Install dependencies python-blosc2
      run: pip install -r python-blosc2/requirements-doc.txt

    # Build websites
    - name: Build Nikola website
      uses: getnikola/nikola-action@v3
      with:
        dry_run: true
    - name: ls
      run: ls
    - name: Build c-blosc2 docs
      run: sphinx-build -b html c-blosc2/doc/sphinx/source output/c-blosc2
    - name: Build python-blosc2 docs
      run: sphinx-build -b html python-blosc2/doc output/python-blosc2

    # Deploy
    - name: Create blosc website artifact
      uses: actions/upload-artifact@v3
      with:
        name: blosc-website
        path: output/

