on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ update_website ]
  pull_request:
    branches: [ master ]

jobs:
  build_website:
    runs-on: ubuntu-latest
    name: 'Build website'
    steps:

    # Set up environment
    - name: Check out website repo
      uses: actions/checkout@v2
    - name: Set up environment and install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        activate-environment: blosc-docs
        environment-file: doc/environment.yml

    # blosc.org (nikola)
    - name: Build Nikola website
      uses: getnikola/nikola-action@v5
      with:
        dry_run: true
    - name: Create artifact directory
      # The Nikola action creates `output/` as root, and it's not writeable
      # `_site/` is the default directory for the upload/deploy pages actions
      run: mkdir _site && cp -r output/* _site/

    # blosc.org/c-blosc2
    - name: Check out C-Blosc2
      run: git clone https://github.com/Blosc/c-blosc2.git
    - name: Build C-Blosc2 docs
      # TODO: Fix warnings in the build and restore `-W` parameter
      run: sphinx-build c-blosc2/doc _site/c-blosc2
      shell: bash -l {0}

    # blosc.org/python-blosc
    - name: Check out Python-Blosc
      run: git clone --recurse-submodules https://github.com/Blosc/python-blosc.git
    - name: Build Python-Blosc
      run: cd python-blosc && python setup.py build
      shell: bash -l {0}
    - name: Install Python-Blosc
      run: pip install -e $(pwd)/python-blosc/
      shell: bash -l {0}
    - name: Build Python-Blosc docs
      # TODO: Fix warnings in the build and restore `-W` parameter
      run: cd python-blosc && sphinx-build doc ../_site/python-blosc
      shell: bash -l {0}

    # blosc.org/python-blosc2
    - name: Check out Python-Blosc2
      run: git clone --recurse-submodules https://github.com/Blosc/python-blosc2.git
    - name: Install pandoc
      run: sudo apt install pandoc
      shell: bash -l {0}
    - name: Install Python-Blosc2 doc dependencies
      run: cd python-blosc2 && pip install -r requirements-doc.txt
      shell: bash -l {0}
    - name: Build Python-Blosc2
      run: cd python-blosc2 && python setup.py build_ext --inplace
      shell: bash -l {0}
    - name: Install Python-Blosc2
      run: pip install -e $(pwd)/python-blosc2/
      shell: bash -l {0}
    - name: Build Python-Blosc2 docs
      # TODO: Fix warnings in the build and restore `-W` parameter
      run: sphinx-build python-blosc2/doc _site/python-blosc2
      shell: bash -l {0}

    # upload artifact
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1

  deploy_website:
    needs: build_website
    if: ${{ github.event_name == 'push' || github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    name: 'Deploy website'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
